#!/bin/bash

elf="$1"
if [ -z "$elf" ]; then
	echo usage: \`genhooks \<elf\>\`
	exit
fi

symtbl="$(mktemp)"
mips64-nm "$elf" | awk '(/^[0-9A-Za-z_ ]*$/) {printf "sym_%s=0x%s\n",$3,substr($1,length($1)-7)}' >"$symtbl"
. "$symtbl"
rm -f "$symtbl"

gsc16()
{
    addr="$(printf "%d" "$1")"
    addr="$(expr "$addr" % 16777216 + 2164260864)" # addr = addr & 0x00FFFFFF | 0x81000000
    val="$(printf "%d" "$2")"
    val="$(expr "$val" % 65536)" # val = val & 0xFFFF
    printf "%08X %04X\n" "$addr" "$val"
}

genhook()
{
    addr="$(printf "%d" "$1")"
    tmp="$(mktemp)"
    echo ".set noreorder; .set noat; $2" | mips64-as - -o "$tmp"
    mips64-readelf -x .text "$tmp" | grep "0x[0-9A-Fa-f]\{8\}" | grep -o " [0-9A-Fa-f]\{8\}" |
    while read -r line; do
        gsc16 "$addr" "0x`echo "$line" | sed -e "s/\(....\)..../\1/"`"
        addr="$(expr "$addr" + 2)"
        gsc16 "$addr" "0x`echo "$line" | sed -e "s/....\(....\)/\1/"`"
        addr="$(expr "$addr" + 2)"
    done
    rm -f "$tmp"
}

genhook "$sym_z2_input_hook" "jal $sym_input_hook;"
genhook "$sym_z2_main_hook" "jal $sym__start;"
genhook "$sym_z2_motion_blur_hook" "jal $sym_motion_blur_hook;"
genhook "$sym_z2_draw_actors_hook" "jal $sym_draw_actors_hook;"
genhook "$sym_z2_draw_room_1_hook" "jal $sym_draw_room_hook;"
genhook "$sym_z2_draw_room_2_hook" "jal $sym_draw_room_hook;"
genhook "$sym_z2_camera_update_hook" "jal $sym_camera_hook;"

if [ "$2" == "lite" ]; then
	genhook "$sym_z2_set_heap" "la \$t8, 0x80700000;"
fi